version: '3.3'
volumes:
  mongo-1-data:
  mongo-2-data:
  mongo-3-data:
services:
  mongo-1:
    image: mongo:3.4
    volumes:
      - mongo-1-data:/data
    ports:
      - "27020:27017"
    command: mongod --replSet WOLOLO-DB

  mongo-2:
    image: mongo:3.4
    volumes:
      - mongo-2-data:/data
    ports:
      - "27021:27017"
    command: mongod --replSet WOLOLO-DB

  mongo-3:
    image: mongo:3.4
    volumes:
      - mongo-3-data:/data
    ports:
      - "27022:27017"
    links:
      - mongo-1:mongo-1
      - mongo-2:mongo-2
    command: mongod --replSet WOLOLO-DB

  mongo-rs-setup:
    container_name: "mongo-rs-setup"
    image: mongo:3.4
    depends_on:
        - "mongo-1"
        - "mongo-2"
        - "mongo-3"
    links:
        - mongo-1:mongo-1
        - mongo-2:mongo-2
        - mongo-3:mongo-3
    volumes:
        - ./scripts:/scripts
    environment: 
        - MONGO1=mongo-1
        - MONGO2=mongo-2
        - MONGO3=mongo-3
        - RS=WOLOLO-DB
        - CHECK_RESTORE=true
        - GOOGLE_DRIVE_ID=1alJev7sV-5tRcc0bi-W4NODGOab70Jos
        - DB_TO_RESTORE=uhul
    entrypoint: [ "/scripts/setup.sh" ]